version: '3.8'

services:
  # Tu API existente
  api:
    build: 
      context: ./apps/api
      dockerfile: Dockerfile
      args:
        DEBUG: 1
    ports:  
      - "8000:8000"
      - "5678:5678"
    environment:
      PYTHONPATH: /app/src
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/scripts:/app/scripts
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./.pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
